services:
  challenge-service:
    build:
      context: .
      dockerfile: challenge-service/Dockerfile
    environment:
      SERVER_PORT: 8081
    ports:
      - "8081:8081"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      SERVER_PORT: 8082
    ports:
      - "8082:8082"