server {
  listen 80;
  server_name _;

  # USER API
  location /itachallenge/api/v1/users/ {
    proxy_pass http://account-service:8080/itachallenge/api/v1/users/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # CHALLENGE API
  location /itachallenge/api/v1/challenges/ {
    proxy_pass http://challenge-service:8080/itachallenge/api/v1/challenges/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /actuator/users/ {
    proxy_pass http://account-service:8080/actuator/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /actuator/challenges/ {
    proxy_pass http://challenge-service:8080/actuator/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    proxy_pass http://frontend:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
