server {
  listen 80;
  server_name _;

  # ACCOUNT
  location /api/account/ {
    proxy_pass http://account-service:8080;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # OAUTH2 - GitHub login flow
  location /api/account/oauth2/ {
    proxy_pass http://account-service:8080;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # LOGIN - OAuth2 callback
  location /api/account/login/ {
    proxy_pass http://account-service:8080;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # USERS
  location /itachallenge/api/v1/users {
    proxy_pass http://account-service:8080/api/v1/users;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # CHALLENGES
  location /itachallenge/api/v1/challenges {
    proxy_pass http://challenge-service:8080/api/v1/challenges;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # ACTUATORS
  location /actuator/users/ {
    proxy_pass http://account-service:8080/actuator/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /actuator/challenges/ {
    proxy_pass http://challenge-service:8080/actuator/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # FRONTEND
  location / {
    proxy_pass http://frontend:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
