spring:
  application:
    name: challenge-service
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: ${SERVER_PORT:8081}
